### ISSUE TITLE
SOP logo unset mix-blend-mode

### ISSUE THREAD

**Issue by megrymo** [SomeoddpilotInc/someoddpilot#55]
Please make a class that will be conditionally added to unset the mix-blend-mode on the SOP header logo.

**Comment by megrymo** [comment]
Apply this to Second City and Sebago case studies.

**Comment by kenworthyc** [comment]
Resolved with [5677ce](https://github.com/SomeoddpilotInc/someoddpilot/commit/5677ce90ec9fe74ad6ebcb1ab769881ff3fc5533). On case study yamls, add boolean `headerNoBlend` at the root.

**Comment by kenworthyc** [comment]
Added to Sebago on [9f9c2e](https://github.com/SomeoddpilotInc/someoddpilot/commit/9f9c2eccc17f9a0f3ba64c1ea4ceb260ef5b34c3)

**Comment by kenworthyc** [comment]
@megrymo @krispy1298 okay to close?

**Comment by kenworthyc** [comment]
Just as a note, this no mix-blend-mode case was an accident on Colleen's part, and it carried over from the v3 case study redesign for Second City and Chaco. But it was ultimately accidental. Don't forget to check with the designers occasionally is the lesson I'm taking from this one.
