### ISSUE TITLE
Stats data partners

### ISSUE THREAD

**Issue by megrymo** [SomeoddpilotInc/someoddpilot#59]
Can these stack more on mobile? I know this is saved as one image now, but could it be two that would `display: inline-block;` on desktop and `display: block;` on mobile? It's just impossible to read these logos on mobile as is.

**Comment by krispy1298** [comment]
This resolved?

**Comment by kenworthyc** [comment]
Not yet. Becca is redesigning that slide– I'll check with her about it.

**Comment by kenworthyc** [comment]
Resolved with [`750bbac`](https://github.com/SomeoddpilotInc/someoddpilot/commit/750bbacfc92d7c0fedb06c2dac4c17cded054365)  🎉
