### ISSUE TITLE
The Quiet Life Title too low

### ISSUE THREAD

**Issue by jeludkov29** [SomeoddpilotInc/someoddpilot#80]
Case Study Title too low

![screen shot 2017-05-09 at 2 47 27 pm](https://cloud.githubusercontent.com/assets/16415762/25869983/09caa58c-34c8-11e7-9ca2-50e1e1844e9f.png)

**Comment by krispy1298** [comment]
@kenworthyc did you check all viewports (variations of thin, wide, tall, short)?

**Comment by kenworthyc** [comment]
@krispy1298 yes– this is the only collision I found. not a realistic viewport size, imo.
![quiet life](https://cloud.githubusercontent.com/assets/8725058/25874935/7106c9da-34da-11e7-8692-dc8b6f9e8bbd.png)

**Comment by krispy1298** [comment]
that's how my tamagotchi sees our site. he's not pleased.

**Comment by krispy1298** [comment]
This can close out after a push.
