### ISSUE TITLE
Text within image expands outside image container

### ISSUE THREAD

**Issue by kenworthyc** [SomeoddpilotInc/someoddpilot#98]
On process page, when viewport is wide-tablet size – between 980px and 1350px wide.

![process-text-slide](https://user-images.githubusercontent.com/8725058/26883560-237969b2-4b63-11e7-9712-ec67cfcaa704.png)

**Comment by krispy1298** [comment]
This is due to https://github.com/SomeoddpilotInc/someoddpilot/commit/dc25b0ab08ab0496256d5c833ba764d84605aa5a#diff-207ffaa19f8743ed1262498aa113e7bcR768
